site_name: 逆引きKotlin
site_url: http://kotlin-rev-solution.herokuapp.com/site
repo_url: https://github.com/yyYank/kotlin-rev-solution
site_description: JVM言語、Kotlin(ことりん)の逆引きサイトです。基本的な環境導入、文法から、あんなことがしたいこんなことがしたいというKotlinでやりたいことを網羅的に逆引き出来るサイトを目指しています。
site_author: yy_yank
theme_dir: 'themes'
pages:
- [index.md, Home]
- [kotlin-install.md, '導入', 'Kotlinをインストールする']
- [kotlin-plugin-intellij.md, '導入', 'KotlinプラグインをIntelliJ IDEAに導入する']
- [kotlin-plugin-androidstudio.md, '導入', 'KotlinプラグインをAndroid Studioに入れる']
- [kotlin-plugin-eclipse.md, '導入', 'KotlinをEclipseで動かす']
- [hello-kotlin-android.md, '導入', 'AndroidでHelloWorld']
- [variable.md, '基本文法', '変数を宣言する']
- [type.md, '基本文法', '型を宣言する']
- [instance.md, '基本文法', 'インスタンスを生成する']
- [array.md, '基本文法', '配列を生成する']
- [function.md, '基本文法', '関数を宣言する']
- [function_type.md, '基本文法', '好きなタイミングで特定の処理を行う']
- [function_object.md, '基本文法', '関数をオブジェクトとして使う']
- [if-statement.md, '基本文法', '条件分岐を行う']
- [if-function.md, '基本文法', 'ifを式として扱う']
- [when.md, '基本文法', 'switchみたいな条件分岐がしたい']
- [loop.md, '基本文法', 'ループ処理を行う']
- [collection-for-each.md, 'コレクション操作', 'リストの要素分ループして操作する']
- [collection-filter.md, 'コレクション操作', '条件でリストを絞り込む']
- [collection-map.md, 'コレクション操作', 'リストの要素の名前のみを抽出する']
- [collection-merge.md, 'コレクション操作', 'リストをマージする']
- [collection-sum.md, 'コレクション操作', 'リストの値を集計する']
- [collection-drop.md, 'コレクション操作', 'リストの要素を前からいくつか削る']
- [collection-take.md, 'コレクション操作', 'リストの要素を前からいくつか取り出す']
- [collection-zip.md, 'コレクション操作', '２つのリストのペアのリストを作る']
- [extension.md, '機能拡張', 'クラスの機能拡張をしたい']
- [type-safe-builder.md, '応用編', '親子関係のある独自のブロックを作りたい']
- [reflection.md, 'リフレクション', 'クラスのメタデータを操作する']
